"""add_last_reminder_sent_at

Revision ID: 3c16a69895c2
Revises: 831aa5c9d10c
Create Date: 2026-07-19 12:06:36.657617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c16a69895c2'
down_revision: Union[str, Sequence[str], None] = '831aa5c9d10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_reminder_sent_at')
    # ### end Alembic commands ###
