"""Add unlocked_skills and skill_points to User

Revision ID: 676a39043c3b
Revises: 0d07847db3c1
Create Date: 2026-07-16 11:39:56.221779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676a39043c3b'
down_revision: Union[str, Sequence[str], None] = '0d07847db3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unlocked_skills', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('skill_points', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skill_points')
    op.drop_column('users', 'unlocked_skills')
    # ### end Alembic commands ###
