"""add_daily_activity_communication_and_task_assignments

Revision ID: 75e00a5005a0
Revises: 0975cb4c08ad
Create Date: 2026-07-10 23:55:18.029540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e00a5005a0'
down_revision: Union[str, Sequence[str], None] = '0975cb4c08ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('blockers', sa.String(length=500), nullable=True),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('hours_spent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('mentor_feedback', sa.String(length=1000), nullable=True),
    sa.Column('mentor_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'date', name='uq_daily_report_user_project_date')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_messages_id'), 'room_messages', ['id'], unique=False)
    op.create_table('daily_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_todos_id'), 'daily_todos', ['id'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignments_id'), 'task_assignments', ['id'], unique=False)
    op.create_table('task_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('demo_url', sa.String(length=255), nullable=True),
    sa.Column('approach_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('mentor_score', sa.Integer(), nullable=True),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submissions_id'), 'task_submissions', ['id'], unique=False)
    
    # Modify tasks table: add new columns
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_mode', sa.String(length=50), nullable=False, server_default='individual'))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # --- DATA MIGRATION: Copy existing assignments to task_assignments ---
    bind = op.get_bind()
    results = bind.execute(sa.text("SELECT id, assigned_to_id, status FROM tasks WHERE assigned_to_id IS NOT NULL")).fetchall()
    
    import datetime
    now = datetime.datetime.now(datetime.timezone.utc)
    
    for task_id, user_id, task_status in results:
        assignment_status = "assigned"
        if task_status == "in_progress":
            assignment_status = "in_progress"
        elif task_status == "review":
            assignment_status = "submitted"
        elif task_status == "done":
            assignment_status = "reviewed"
            
        bind.execute(
            sa.text(
                "INSERT INTO task_assignments (task_id, user_id, assigned_by_id, assigned_at, status) "
                "VALUES (:task_id, :user_id, NULL, :assigned_at, :status)"
            ),
            {"task_id": task_id, "user_id": user_id, "assigned_at": now, "status": assignment_status}
        )
    # ---------------------------------------------------------------------

    # Modify tasks table: drop assigned_to_id column
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add assigned_to_id back to tasks
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('tasks_assigned_to_id_fkey', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')

    # --- REVERSE DATA MIGRATION: Restore assigned_to_id from task_assignments ---
    bind = op.get_bind()
    results = bind.execute(sa.text(
        "SELECT task_id, user_id FROM task_assignments WHERE id IN "
        "(SELECT MIN(id) FROM task_assignments GROUP BY task_id)"
    )).fetchall()
    
    for task_id, user_id in results:
        bind.execute(
            sa.text("UPDATE tasks SET assigned_to_id = :user_id WHERE id = :task_id"),
            {"user_id": user_id, "task_id": task_id}
        )
    # -----------------------------------------------------------------------------

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('task_mode')

    op.drop_index(op.f('ix_task_submissions_id'), table_name='task_submissions')
    op.drop_table('task_submissions')
    op.drop_index(op.f('ix_task_assignments_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_daily_todos_id'), table_name='daily_todos')
    op.drop_table('daily_todos')
    op.drop_index(op.f('ix_room_messages_id'), table_name='room_messages')
    op.drop_table('room_messages')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
