"""add approval workflows

Revision ID: 831aa5c9d10c
Revises: d7e3fdf51900
Create Date: 2026-07-19 11:41:20.503653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831aa5c9d10c'
down_revision: Union[str, Sequence[str], None] = 'd7e3fdf51900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_approval_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_approval_messages_id'), 'project_approval_messages', ['id'], unique=False)
    op.add_column('projects', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'status')
    op.drop_column('projects', 'rejection_reason')
    op.drop_index(op.f('ix_project_approval_messages_id'), table_name='project_approval_messages')
    op.drop_table('project_approval_messages')
    # ### end Alembic commands ###
